version: '3'
networks:
  expense:
volumes: #docker volume create mysql
  mysql: 
services: # docker run -d mysql:v1 
  mysql: 
    image: mahadevan045/mysql:v1 
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql

  backend:
    image: mahadevan045/backend:v1
    command: sh -c "sleep 5 && node /opt/server/index.js"
    container_name: backend 
    depends_on:
    - mysql
  
  frontend:
    image: mahadevan045/frontend:v1
    container_name: frontend
    depends_on:
    - backend
    ports:
      - "80:80"